services:
  web:
    build: .
    command: >
      sh -c "
        poetry run python manage.py makemigrations &&
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "poetry", "run", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16.9-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: >
      sh -c "
        poetry run celery -A core worker --loglevel=info
      "
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "poetry", "run", "celery", "-A", "core", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  flower:
    build: .
    command: >
      sh -c "
        poetry run celery -A core flower --broker=redis://redis:6379/0 --address=0.0.0.0 --port=5555
      "
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: